In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
import matplotlib.pyplot as plt
import scipy.stats as stats
import json
from collections import Counter
import random
import seaborn as sns

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

**Import Safegraph geometry**
Just ONE of these two cells (Massachusetts or the US)

In [ ]:
#These are the parts of the geometry core from Safegraph. These parts are for US, owned and shared polygon
part1 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part1.csv')
part2 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part2.csv')
part3 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part3.csv')
part4 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part4.csv')
part5 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part5.csv')
part6 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part6.csv')
part7 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part7.csv')
part8 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part8.csv')
part9 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part9.csv')
part10 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part10.csv')
part11 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part11.csv')
part12 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part12.csv')
part13 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part13.csv')
part14 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part14.csv')
part15 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part15.csv')
part16 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part16.csv')
part17 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part17.csv')
part18 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part18.csv')
part19 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part19.csv')
part20 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part20.csv')
part21 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part21.csv')
part22 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part22.csv')
part23 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part23.csv')
part24 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part24.csv')
part25 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part25.csv')
part26 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part26.csv')
part27 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part27.csv')
part28 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part28.csv')
part29 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part29.csv')
part30 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part30.csv')
part31 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part31.csv')
part32 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part32.csv')
part33 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part33.csv')
part34 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part34.csv')
part35 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part35.csv')
part36 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part36.csv')
part37 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part37.csv')
part38 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part38.csv')
part39 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part39.csv')
part40 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part40.csv')
part41 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part41.csv')
part42 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part42.csv')
part43 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part43.csv')
part44 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part44.csv')
part45 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part45.csv')
part46 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part46.csv')
part47 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part47.csv')
part48 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part48.csv')
part49 = pd.read_csv('drive/MyDrive/Amenities/data/US_geometry/Copy of part49.csv')

**Merge all the pattern parts**

In [ ]:
geom_us = pd.concat([part1, part2, part3, part4, part5, part6, part7, part8, part9, part10,
                     part11, part12, part13, part14, part15, part16, part17, part18, part19, part20,
                    part21, part22, part23, part24, part25, part26, part27, part28, part29, part30,
                     part31, part32, part33, part34, part35, part36, part37, part38, part39, part40,
                     part41, part42, part43, part44, part45, part46, part47, part48, part49,]).reset_index().drop('index', axis = 1)
geom_us.head(2)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_wkt,polygon_class,enclosed,wkt_area_sq_meters
0,222-222@5rj-nxb-nnq,"Agencies, Brokerages, and Other Insurance Rela...",Insurance Agencies and Brokerages,524210.0,MN,55746.0,NaN,POLYGON,POLYGON ((-92.94189116799998 47.42240852800006...,OWNED_POLYGON,False,362.0
1,zzw-222@8tj-h2b-bkz,"Justice, Public Order, and Safety Activities",Fire Protection,922160.0,NM,88232.0,NaN,POLYGON,POLYGON ((-104.32497579799997 33.1138842100000...,OWNED_POLYGON,False,1040.0

In [ ]:
geom_us['placekey'].nunique()

10861811

In [ ]:
geom_us=geom_us[geom_us['region']=='MA']
#geom_us=geom_us[geom_us['polygon_class']=='OWNED_POLYGON']
geom_us.reset_index
geom_us.head(2)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_wkt,polygon_class,enclosed,wkt_area_sq_meters
32,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,"POLYGON ((-71.082118275593 42.370538630736945,...",SHARED_POLYGON,False,754.0
65,zzy-222@62j-syn-nh5,Urban Transit Systems,Bus and Other Motor Vehicle Transit Systems,485113.0,MA,2151.0,NaN,POINT,NaN,NaN,NaN,NaN

In [ ]:
geom_us['placekey'].nunique()

137226

In [ ]:
len(geom_us)

137226

In [ ]:
geom_us=geom_us.drop_duplicates(subset=['placekey']).reset_index().drop('index', axis = 1)
geom_us.head(2)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_wkt,polygon_class,enclosed,wkt_area_sq_meters
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,"POLYGON ((-71.082118275593 42.370538630736945,...",SHARED_POLYGON,False,754.0
1,zzy-222@62j-syn-nh5,Urban Transit Systems,Bus and Other Motor Vehicle Transit Systems,485113.0,MA,2151.0,NaN,POINT,NaN,NaN,NaN,NaN

In [ ]:
geom_us.to_csv('drive/MyDrive/Amenities/data/geom_ma_ownedandshared.csv', encoding='utf-8', index=False) 

#Take this to geopandas and add the neighborhood to every placekey using the geometry column--> 'geopandas_neighToPOI'

In [ ]:
#Save this data, and use geopandas in jupyter lab to add the blockgroup to each POI

#In addition, using geopandas we will get the blockgroups of the Boston Urban Area we want to study. Then, we will be able to use these blockgroups as a filter 
#to keep just the POIs in Boston Urban Area.

## Import from Geopandas

In [3]:
#Import placekeys with neighborhood from geopandas
geom_ma_bg = pd.read_csv ('drive/MyDrive/Amenities/data/geom_ma_ownedandshared_bgp.csv', index_col = False)
geom_ma_bg=geom_ma_bg.drop('Unnamed: 0', axis=1)
geom_ma_bg.head(2)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_class,enclosed,wkt_area_sq_meters,GEOID,geometry
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,754.0,250173521021,"POLYGON ((-71.082118275593 42.37053863073695, ..."
1,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,142.0,250173521021,"POLYGON ((-71.08218157581375 42.369489054537, ..."

In [4]:
len(geom_ma_bg)

263231

In [5]:
#Import blockgroups in Boston URban Area
BUA_bg = pd.read_csv('drive/MyDrive/Amenities/output/geopandas_BUA_bgp.csv', index_col = False)
BUA_bg.drop('Unnamed: 0', axis=1, inplace=True)
BUA_bg.head(2)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,GEOID,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry,boundary,centroid,intersects
0,25,17,353200,2,250173532002,Block Group 2,G5030,S,150628,0,42.357801,-71.105423,"POLYGON ((-71.109467 42.358362, -71.108813 42....","LINESTRING (-71.109467 42.358362, -71.108813 4...",POINT (-71.10542283047126 42.35780119427952),True
1,25,25,91100,5,250250911005,Block Group 5,G5030,S,66634,0,42.317050,-71.057945,"POLYGON ((-71.059544 42.316202, -71.0594579999...","LINESTRING (-71.059544 42.316202, -71.05945799...",POINT (-71.05794458903385 42.31705043327756),True

In [6]:
len(BUA_bg)

427

## BUA

In [7]:
#Keep the POIs whose is in the list of blockgroups of Boston
POI_BUA = geom_ma_bg[geom_ma_bg['GEOID'].isin(BUA_bg['GEOID'])].reset_index().drop('index', axis = 1)
POI_BUA.head(2)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_class,enclosed,wkt_area_sq_meters,GEOID,geometry
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,754.0,250173521021,"POLYGON ((-71.082118275593 42.37053863073695, ..."
1,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,142.0,250173521021,"POLYGON ((-71.08218157581375 42.369489054537, ..."

In [8]:
len(POI_BUA)

47037

In [9]:
POI_BUA[POI_BUA['naics_code']==488119]

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_class,enclosed,wkt_area_sq_meters,GEOID,geometry
3336,zzw-222@62j-qp7-st9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6893083.0,250250510001,MULTIPOLYGON (((-71.01596488888897 42.38085233...
7821,zzw-222@62j-qp7-st9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6893083.0,250250512002,MULTIPOLYGON (((-71.02954660267757 42.36490320...
27107,zzw-222@62j-sj7-mhq,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,42937.0,250259813002,POLYGON ((-71.02294974131109 42.36986787073735...
27171,zzw-222@62j-qp7-st9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6893083.0,250259813002,"POLYGON ((-71.03107 42.36693, -71.031000000000..."
27207,zzw-223@62j-qp2-fpv,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,71975.0,250259813002,POLYGON ((-71.01956478406197 42.36409656934664...
27263,zzw-222@62j-sj7-jd9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,26297.0,250259813002,POLYGON ((-71.02208787684248 42.36406691677846...
27315,222-23h@62j-sj7-n89,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6313169.0,250259813002,POLYGON ((-71.02090233837633 42.37924035174328...
27347,zzw-222@62j-qp7-tsq,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,31608.0,250259813002,MULTIPOLYGON (((-71.01864702155319 42.36821092...
36023,zzw-222@62j-qp7-st9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6893083.0,250250511013,GEOMETRYCOLLECTION (POINT (-71.00245199999999 ...
36076,222-23h@62j-sj7-n89,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6313169.0,250250511013,MULTIPOLYGON (((-71.00266321663355 42.37833854...
38685,zzw-222@62j-qp7-st9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6893083.0,250250509011,MULTIPOLYGON (((-71.02375272781116 42.37935290...
40084,zzw-222@62j-qp7-st9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6893083.0,250259813001,"POLYGON ((-71.0002141876307 42.37775174484613,..."
40095,222-23h@62j-sj7-n89,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6313169.0,250259813001,POLYGON ((-71.00043387617661 42.37769123509776...
40117,zzw-222@62j-qp7-st9,Support Activities for Air Transportation,Other Airport Operations,488119.0,MA,2128.0,NaN,POLYGON,OWNED_POLYGON,False,6893083.0,250250512001,"MULTIPOLYGON (((-71.02637 42.36268674999967, -..."

In [10]:
len(POI_BUA)

47037

In [11]:
POI_BUA['placekey'].nunique()

43967

In [12]:
POI_BUA=POI_BUA.drop_duplicates(subset=['placekey']).reset_index().drop('index', axis = 1)
POI_BUA.head(2)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_class,enclosed,wkt_area_sq_meters,GEOID,geometry
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,754.0,250173521021,"POLYGON ((-71.082118275593 42.37053863073695, ..."
1,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,142.0,250173521021,"POLYGON ((-71.08218157581375 42.369489054537, ..."

In [13]:
len(POI_BUA)

43967

In [ ]:
realestate_list=[531110, 531120, 531130, 531190, 531210, 531311, 531312, 531320, 531390]
realestate = POI_BUA[POI_BUA['naics_code'].isin(realestate_list)].reset_index().drop('index', axis = 1)
len(realestate)

22463

In [ ]:
len(POI_BUA[POI_BUA['naics_code']==531110])

21500

In [ ]:
specialtyfood_list=[445230, 445240, 445250, 445291, 445292, 445298]
specialtyfood = POI_BUA[POI_BUA['naics_code'].isin(specialtyfood_list)].reset_index().drop('index', axis = 1)
len(specialtyfood)

46

In [ ]:
POI_BUA[POI_BUA['naics_code']==445230]

,GEOID,placekey,region,top_category,sub_category,naics_code,geometry_type,polygon_class,wkt_area_sq_meters,enclosed,geometry
6962,250173531022,222-222@62j-sj2-dn5,MA,Specialty Food Stores,Fruit and Vegetable Markets,445230.0,POLYGON,OWNED_POLYGON,144.0,False,POLYGON ((-71.08856402048296 42.35989044689089...
7248,250173536005,zzy-222@62j-sjv-brk,MA,Specialty Food Stores,Fruit and Vegetable Markets,445230.0,POLYGON,OWNED_POLYGON,3472.0,False,POLYGON ((-71.11684496746203 42.37669325430878...
18164,250250303003,225-229@62j-shx-ffz,MA,Specialty Food Stores,Fruit and Vegetable Markets,445230.0,POLYGON,OWNED_POLYGON,464.0,False,"POLYGON ((-71.0575601153197 42.36168010392831,..."

**Replica (Population)**
Read Boston Urban Area

In [14]:
#Import population in Boston
boston_pop = pd.read_csv ('drive/MyDrive/Amenities/output/bigquery_BUA_population.csv', index_col = False)
boston_pop['person_id'] = boston_pop['person_id'].astype(float)
boston_pop.head(2)

,household_id,person_id,BLOCKGROUP,age,individual_income,household_size,household_income,family_structure,vehicles
0,7670780544235756806,1.208496e+19,250173537002,88,178836,2_person,244316,nonfamily_single,1
1,12636066713864596213,1.707506e+19,250214010003,88,54048,3_person,80556,married_couple,1

In [15]:
BUA_pop=len(boston_pop)

In [16]:
BUA_pop

551387

# COUNT POIs PER AME

**Merge with amenities**

In [17]:
#Import csv with name of amenities based on naics code
amenities_name = pd.read_csv ('drive/MyDrive/Amenities/data/Amenities_name_3.csv', index_col = False)
amenities_name.head()

   naics_code travel_purpose top_amenity sub_amenity
0      111110           Work        Agro        Agro
1      111120           Work        Agro        Agro
2      111130           Work        Agro        Agro
3      111140           Work        Agro        Agro
4      111150           Work        Agro        Agro

In [18]:
POI_BUA= POI_BUA.merge(amenities_name[['naics_code', 'sub_amenity']], on='naics_code', how = 'left').reset_index().drop('index', axis = 1)
POI_BUA.head()

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_class,enclosed,wkt_area_sq_meters,GEOID,geometry,sub_amenity
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,754.0,250173521021,"POLYGON ((-71.082118275593 42.37053863073695, ...",Real Estate
1,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,142.0,250173521021,"POLYGON ((-71.08218157581375 42.369489054537, ...",Real Estate
2,223-222@62j-shx-t35,Traveler Accommodation,Hotels (except Casino Hotels) and Motels,721110.0,MA,2142.0,NaN,POLYGON,OWNED_POLYGON,False,2569.0,250173521021,POLYGON ((-71.07426532699998 42.36722293300005...,Hotel and Lodging
3,222-223@62j-shx-qs5,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2142.0,NaN,POLYGON,OWNED_POLYGON,False,986.0,250173521021,POLYGON ((-71.07677258899997 42.36487600900006...,Real Estate
4,zzw-224@62j-shx-tjv,"Other Professional, Scientific, and Technical ...",Photographic Services,54192.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,True,35065.0,250173521021,POLYGON ((-71.07532651299994 42.36837735200004...,NaN

In [19]:
#Number of placekeys with no sub_amenity
len(POI_BUA[POI_BUA['sub_amenity'].isnull()])

5113

In [20]:
len(POI_BUA)

43967

In [21]:
#naics codes of placekeys with no subamenity
POI_BUA[POI_BUA['sub_amenity'].isnull()]['naics_code'].unique()

array([5.41920e+04, 4.48100e+03, 2.38300e+03, 4.87000e+02, 8.12110e+04,
       3.39900e+03, 4.42200e+03, 3.23100e+03, 8.11100e+03, 5.41600e+03,
       5.41800e+03, 2.38200e+03, 4.23800e+03, 5.41200e+03, 5.61600e+03,
       7.21200e+03, 5.61500e+03, 6.11500e+03, 5.15100e+03, 2.38900e+03,
       4.44100e+03, 6.21400e+03, 4.85000e+02, 5.62000e+02, 9.26100e+03,
       5.41400e+03, 6.21500e+03, 7.11100e+03, 4.44200e+03, 4.82100e+03,
       4.52311e+05, 4.83000e+02, 6.23000e+02, 8.12200e+03, 8.11212e+05,
       9.23100e+03, 3.16998e+05, 2.36100e+03, 6.24100e+03, 6.24000e+02,
       6.23300e+03, 9.22100e+03])

In [22]:
#Erase the rows with no naics_code
POI_BUA = POI_BUA[POI_BUA.naics_code.notnull()].reset_index().drop('index', axis = 1)

In [23]:
# Count the number of placekeys per amenity 
POI_per_ame = POI_BUA.groupby(['sub_amenity',])['placekey'].count().reset_index().sort_values(by='placekey', ascending = False).rename(columns = {'placekey':'count_POIs'}).reset_index().drop('index', axis = 1)
POI_per_ame.head(10)

                                 sub_amenity  count_POIs
0                                Real Estate       22463
1                   Full-Service Restaurants        1757
2  Offices of Physicians (not mental health)        1579
3                                  Hospitals        1067
4                                        Gym         998
5                                    Finance         980
6      Snack and Nonalcoholic Beverage Bars          550
7                          Religious Centers         531
8               Limited-Service Restaurants          520
9                        Offices of Dentists         473

In [24]:
#Create a column with the first 3 digits (because some placekeys have just 3 digits) of the naics_code for every placekey and amenity name
amenities_name['naics_3'] = amenities_name['naics_code'].astype(str).str[:3].astype(int)
POI_BUA['naics_3'] = POI_BUA['naics_code'].astype(str).str[:3].astype(int)
amenities_name = amenities_name.merge(POI_per_ame[['sub_amenity', 'count_POIs']], on='sub_amenity', how = 'left')
amenities_name.head(2)

   naics_code travel_purpose top_amenity sub_amenity  naics_3  count_POIs
0      111110           Work        Agro        Agro      111         2.0
1      111120           Work        Agro        Agro      111         2.0

In [25]:
#Associate an amenity name to the unregistered naics codes 
for i in range(len(POI_BUA)):
  #Extract the sub_amenity name of the trip. If it is Nan, then we will have to look for an approximate naics code
  aux=POI_BUA.at[i, 'sub_amenity']
  if (isinstance(aux, str)==False):
  # Extracting the 3 digits naics code of the trip 
    naics=POI_BUA.at[i, 'naics_3']
  
  # Take the sub amenities that coincide with that naics code
    possible_sub_amenities = amenities_name[(amenities_name['naics_3'] == naics)]

  # Condition true if any sub_amenity meet the condition
    if (possible_sub_amenities.empty == False):
    # Weighted randomization association based on Safegraph’s registered POIs. The first argument is the list of objects from which it must select one and the second argument is 
    # the list of weights for each object of the list. Therefore, the sub_amenity with more POIs will be selected.
      POI_BUA.at[i, 'sub_amenity'] = random.choices(list(possible_sub_amenities['sub_amenity']), list(possible_sub_amenities['count_POIs']))[0]

POI_BUA.head(10)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_class,enclosed,wkt_area_sq_meters,GEOID,geometry,sub_amenity,naics_3
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,754.0,250173521021,"POLYGON ((-71.082118275593 42.37053863073695, ...",Real Estate,531
1,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,142.0,250173521021,"POLYGON ((-71.08218157581375 42.369489054537, ...",Real Estate,531
2,223-222@62j-shx-t35,Traveler Accommodation,Hotels (except Casino Hotels) and Motels,721110.0,MA,2142.0,NaN,POLYGON,OWNED_POLYGON,False,2569.0,250173521021,POLYGON ((-71.07426532699998 42.36722293300005...,Hotel and Lodging,721
3,222-223@62j-shx-qs5,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2142.0,NaN,POLYGON,OWNED_POLYGON,False,986.0,250173521021,POLYGON ((-71.07677258899997 42.36487600900006...,Real Estate,531
4,zzw-224@62j-shx-tjv,"Other Professional, Scientific, and Technical ...",Photographic Services,54192.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,True,35065.0,250173521021,POLYGON ((-71.07532651299994 42.36837735200004...,Professional Services,541
5,2cb-234@62j-shx-hqz,"Sporting Goods, Hobby, and Musical Instrument ...",Sporting Goods Stores,451110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,True,35065.0,250173521021,POLYGON ((-71.07532651299994 42.36837735200004...,Hobby retailers,451
6,zzw-22g@62j-shx-tjv,Health and Personal Care Stores,"Cosmetics, Beauty Supplies, and Perfume Stores",446120.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,True,35065.0,250173521021,POLYGON ((-71.07532651299994 42.36837735200004...,Cosmetics Retail,446
7,223-223@62j-shx-k2k,Other Personal Services,All Other Personal Services,812990.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,69.0,250173521021,POLYGON ((-71.07861956699998 42.36968320100004...,Other Personal Care Services,812
8,22c-222@62j-sj3-54v,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,135.0,250173521021,POLYGON ((-71.08103693799995 42.36912611100007...,Real Estate,531
9,zzw-222@62j-shx-jvz,Restaurants and Other Eating Places,Full-Service Restaurants,722511.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,113.0,250173521021,POLYGON ((-71.07709571187981 42.36942900256568...,Full-Service Restaurants,722

In [26]:
#Import amenities classification (sub-top-purpose) to add to each sub_amenity its top_amenity and travel_purpose
amenities_classification = pd.read_csv ('drive/MyDrive/Amenities/data/Amenities_classification.csv', index_col = False)

POI_BUA= POI_BUA.merge(amenities_classification[['travel_purpose', 'top_amenity', 'sub_amenity']], on='sub_amenity', how = 'left')
POI_BUA.head(10)

,placekey,top_category,sub_category,naics_code,region,postal_code,closed_on,geometry_type,polygon_class,enclosed,wkt_area_sq_meters,GEOID,geometry,sub_amenity,naics_3,travel_purpose,top_amenity
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,754.0,250173521021,"POLYGON ((-71.082118275593 42.37053863073695, ...",Real Estate,531,Errands,Professional Services
1,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,142.0,250173521021,"POLYGON ((-71.08218157581375 42.369489054537, ...",Real Estate,531,Errands,Professional Services
2,223-222@62j-shx-t35,Traveler Accommodation,Hotels (except Casino Hotels) and Motels,721110.0,MA,2142.0,NaN,POLYGON,OWNED_POLYGON,False,2569.0,250173521021,POLYGON ((-71.07426532699998 42.36722293300005...,Hotel and Lodging,721,Recreation,Hotel
3,222-223@62j-shx-qs5,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2142.0,NaN,POLYGON,OWNED_POLYGON,False,986.0,250173521021,POLYGON ((-71.07677258899997 42.36487600900006...,Real Estate,531,Errands,Professional Services
4,zzw-224@62j-shx-tjv,"Other Professional, Scientific, and Technical ...",Photographic Services,54192.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,True,35065.0,250173521021,POLYGON ((-71.07532651299994 42.36837735200004...,Professional Services,541,Errands,Professional Services
5,2cb-234@62j-shx-hqz,"Sporting Goods, Hobby, and Musical Instrument ...",Sporting Goods Stores,451110.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,True,35065.0,250173521021,POLYGON ((-71.07532651299994 42.36837735200004...,Hobby retailers,451,Shop,Retail (Consumer Goods)
6,zzw-22g@62j-shx-tjv,Health and Personal Care Stores,"Cosmetics, Beauty Supplies, and Perfume Stores",446120.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,True,35065.0,250173521021,POLYGON ((-71.07532651299994 42.36837735200004...,Cosmetics Retail,446,Shop,Retail (Consumer Goods)
7,223-223@62j-shx-k2k,Other Personal Services,All Other Personal Services,812990.0,MA,2141.0,NaN,POLYGON,SHARED_POLYGON,False,69.0,250173521021,POLYGON ((-71.07861956699998 42.36968320100004...,Other Personal Care Services,812,Errands,Leisure & Wellness
8,22c-222@62j-sj3-54v,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,135.0,250173521021,POLYGON ((-71.08103693799995 42.36912611100007...,Real Estate,531,Errands,Professional Services
9,zzw-222@62j-shx-jvz,Restaurants and Other Eating Places,Full-Service Restaurants,722511.0,MA,2141.0,NaN,POLYGON,OWNED_POLYGON,False,113.0,250173521021,POLYGON ((-71.07709571187981 42.36942900256568...,Full-Service Restaurants,722,Eat,F&B Eatery

In [27]:
#Number of placekeys with no sub_amenity
len(POI_BUA[POI_BUA['sub_amenity'].isnull()])

0

In [28]:
#Erase the rows with no amenity name
POI_BUA = POI_BUA[POI_BUA.sub_amenity.notnull()].reset_index().drop('index', axis = 1)

In [29]:
POI_BUA=POI_BUA[['placekey', 'top_category', 'sub_category', 'naics_code', 'travel_purpose', 'top_amenity', 'sub_amenity', 'polygon_class', 'wkt_area_sq_meters']]
POI_BUA.head(2)

,placekey,top_category,sub_category,naics_code,travel_purpose,top_amenity,sub_amenity,polygon_class,wkt_area_sq_meters
0,22d-222@62j-sj3-59f,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,Errands,Professional Services,Real Estate,SHARED_POLYGON,754.0
1,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,Errands,Professional Services,Real Estate,OWNED_POLYGON,142.0

In [30]:
# Count the number of placekeys per amenity AGAIN
POI_per_ame = POI_BUA.groupby(['sub_amenity',])['placekey'].count().reset_index().sort_values(by='placekey', ascending = False).rename(columns = {'placekey':'count_POIs'}).reset_index().drop('index', axis = 1)
POI_per_ame.head(10)

                                 sub_amenity  count_POIs
0                                Real Estate       22463
1                   Full-Service Restaurants        1757
2  Offices of Physicians (not mental health)        1584
3                                  Hospitals        1118
4                      Professional Services        1114
5                                        Gym         998
6                                    Finance         980
7        Administrative and Support Services         871
8                              Manufacturing         728
9               Other Repair and Maintenance         620

In [31]:
POI_per_ame[POI_per_ame['sub_amenity']=='Veterinary Services']

            sub_amenity  count_POIs
64  Veterinary Services          35

In [32]:
POI_per_ame['NPOI_p1000']=1000*POI_per_ame['count_POIs']/BUA_pop
POI_per_ame.head(10)

                                 sub_amenity  count_POIs  NPOI_p1000
0                                Real Estate       22463   40.739082
1                   Full-Service Restaurants        1757    3.186510
2  Offices of Physicians (not mental health)        1584    2.872755
3                                  Hospitals        1118    2.027614
4                      Professional Services        1114    2.020360
5                                        Gym         998    1.809981
6                                    Finance         980    1.777336
7        Administrative and Support Services         871    1.579653
8                              Manufacturing         728    1.320307
9               Other Repair and Maintenance         620    1.124437

In [ ]:
POI_BUA.to_csv('drive/MyDrive/Amenities/output/geopandas_geom_BUA_amenitiesadded_ownedandshared.csv', encoding='utf-8', index=False)
POI_per_ame.to_csv('drive/MyDrive/Amenities/output/geopandas_BUA_Teresa_POI_per_ame_ownedandshared.csv', encoding='utf-8', index=False)

In [ ]:
POI_BUA[POI_BUA['sub_amenity']=='Golf Courses']

,placekey,top_category,sub_category,naics_code,travel_purpose,top_amenity,sub_amenity,polygon_class,wkt_area_sq_meters
591,222-22p@62j-shz-45f,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,3858.0
1315,223-224@62j-shz-skf,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,30902.0
2543,zzy-222@62j-shy-w49,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,193.0
4459,zzy-22h@62j-shx-brk,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,SHARED_POLYGON,2438.0
4599,242-229@62j-shx-bp9,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,1111.0
6367,22f-223@62j-sj4-p7q,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,30902.0
8463,23m-222@62j-shz-4y9,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,30902.0
12073,27b-223@62j-sj3-tgk,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,152.0
30437,22x-226@62j-sj6-wx5,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,476.0
33090,zzw-222@62j-qp5-ch5,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,223525.0
33167,222-222@62j-sgw-389,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,484117.0
33431,23g-223@62j-sjp-s5z,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,231.0
33701,222-223@62j-syg-vs5,Other Amusement and Recreation Industries,Golf Courses and Country Clubs,713910.0,Recreation,Leisure & Wellness,Golf Courses,OWNED_POLYGON,291.0

# SIZE INFO

In [33]:
#Erase the rows with null area
trips_aux=POI_BUA[POI_BUA['wkt_area_sq_meters'].notnull()]
#Erase the POIs classified as SHARED POLYGON
trips_aux=POI_BUA[POI_BUA['polygon_class']=='OWNED_POLYGON']

#Get an array with the sub amenities name
sub_amenity_names=trips_aux['sub_amenity'].unique()

#Filter the outliers of the geometry file
trips_filt=pd.DataFrame()
for i in range(len(sub_amenity_names)):
  #Extract the sub amenity name from the array
  sub_amenity=sub_amenity_names[i]
  #Extract the trips to that type of sub amenity
  trips_subam=trips_aux[trips_aux['sub_amenity']==sub_amenity].reset_index()
  #Calculate the  scores
  trips_subam['z_scores'] =stats.zscore(trips_subam['wkt_area_sq_meters'])
  #Take out the outliers
  trips_temp = trips_subam[np.abs(trips_subam['z_scores']) < 3].reset_index().drop('index', axis = 1)
  #Make a dataframe with the filtered trips
  trips_filt=pd.concat([trips_filt, trips_temp])

trips_filt.head(2)

,level_0,placekey,top_category,sub_category,naics_code,travel_purpose,top_amenity,sub_amenity,polygon_class,wkt_area_sq_meters,z_scores
0,0,22r-222@62j-sj3-4sq,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,Errands,Professional Services,Real Estate,OWNED_POLYGON,142.0,-0.202462
1,1,222-223@62j-shx-qs5,Lessors of Real Estate,Lessors of Residential Buildings and Dwellings,531110.0,Errands,Professional Services,Real Estate,OWNED_POLYGON,986.0,0.080636

In [34]:
len(trips_filt)

21279

In [35]:
sz_info_mean = trips_filt.groupby(['travel_purpose', 'top_amenity', 'sub_amenity'])['wkt_area_sq_meters'].mean().reset_index().rename(columns = {'wkt_area_sq_meters': 'mean_sqm'}).sort_values(by = 'mean_sqm', ascending = False)
sz_info_mean.head()

   travel_purpose         top_amenity            sub_amenity      mean_sqm
56         School           Education        Junior Colleges  74978.000000
51     Recreation  Leisure & Wellness           Golf Courses  67221.666667
48     Recreation      Entertainment        Spectator Sports  26311.125000
49     Recreation      Entertainment   Zoos and Nature Parks  19657.685714
59         School           Education           Universities  11302.529412

In [36]:
sz_info_median = trips_filt.groupby(['travel_purpose', 'top_amenity', 'sub_amenity'])['wkt_area_sq_meters'].median().reset_index().rename(columns = {'wkt_area_sq_meters': 'median_sqm'}).sort_values(by = 'median_sqm', ascending = False)
sz_info_median.head()

   travel_purpose         top_amenity            sub_amenity  median_sqm
56         School           Education        Junior Colleges     74978.0
48     Recreation      Entertainment        Spectator Sports     22474.0
49     Recreation      Entertainment   Zoos and Nature Parks      2963.0
54     Recreation  Leisure & Wellness  Recreation Industries      2628.0
59         School           Education           Universities      2579.0

In [37]:
sz_info=sz_info_mean.merge(sz_info_median[['sub_amenity', 'median_sqm']], how= 'left', on= 'sub_amenity')
sz_info.head(2)

,travel_purpose,top_amenity,sub_amenity,mean_sqm,median_sqm
0,School,Education,Junior Colleges,74978.000000,74978.0
1,Recreation,Leisure & Wellness,Golf Courses,67221.666667,2484.5

In [38]:
sz_info['min_sqm']=""
sz_info['max_sqm']=""

for i in range(len(sz_info)):
  #Extract the sub_amenity name of the trip. If it is Nan, then we will have to look for an approximate naics code
  name=sz_info.at[i, 'sub_amenity']
  list_POIs=trips_filt[(trips_filt['sub_amenity']==name)]
  min=list_POIs['wkt_area_sq_meters'].min()
  max=list_POIs['wkt_area_sq_meters'].max()

  sz_info.at[i, 'min_sqm'] = min
  sz_info.at[i, 'max_sqm'] = max

sz_info.head(2)

,travel_purpose,top_amenity,sub_amenity,mean_sqm,median_sqm,min_sqm,max_sqm
0,School,Education,Junior Colleges,74978.000000,74978.0,21881.0,128075.0
1,Recreation,Leisure & Wellness,Golf Courses,67221.666667,2484.5,152.0,484117.0

In [39]:
sz_info.columns

Index(['travel_purpose', 'top_amenity', 'sub_amenity', 'mean_sqm',
       'median_sqm', 'min_sqm', 'max_sqm'],
      dtype='object')

In [40]:
#Total sqm by sub_amenity
total_sqm=trips_filt.groupby(['travel_purpose', 'top_amenity', 'sub_amenity']).agg({'wkt_area_sq_meters': 'sum'}).reset_index().rename(columns = {'wkt_area_sq_meters': 'total_sq_meters'})
total_sqm.head(2)

  travel_purpose top_amenity               sub_amenity  total_sq_meters
0            Eat  F&B Eatery          Drinking Places           16900.0
1            Eat  F&B Eatery  Full-Service Restaurants         205917.0

In [41]:
sz_info=sz_info.merge(total_sqm[['sub_amenity', 'total_sq_meters']], how= 'left', on= 'sub_amenity')
sz_info

,travel_purpose,top_amenity,sub_amenity,mean_sqm,median_sqm,min_sqm,max_sqm,total_sq_meters
0,School,Education,Junior Colleges,74978.000000,74978.0,21881.0,128075.0,149956.0
1,Recreation,Leisure & Wellness,Golf Courses,67221.666667,2484.5,152.0,484117.0,806660.0
2,Recreation,Entertainment,Spectator Sports,26311.125000,22474.0,4485.0,67083.0,210489.0
3,Recreation,Entertainment,Zoos and Nature Parks,19657.685714,2963.0,59.0,863470.0,7568209.0
4,School,Education,Universities,11302.529412,2579.0,173.0,67333.0,576429.0
...,...,...,...,...,...,...,...,...
80,Errands,Leisure & Wellness,Personal Wellness,248.254902,170.0,8.0,1479.0,25322.0
81,Shop,Retail (Consumer Goods),Pet Store,232.000000,205.0,104.0,534.0,1624.0
82,Eat,F&B Eatery,Full-Service Restaurants,224.066376,138.0,7.0,1547.0,205917.0
83,Eat,F&B Eatery,Drinking Places,196.511628,142.0,40.0,835.0,16900.0
84,Errands,Leisure & Wellness,Personal Grooming,156.783784,141.0,34.0,582.0,5801.0

In [42]:
sz_info.to_csv('drive/MyDrive/Amenities/output/geopandas_BUA_Teresa_sz_info.csv', encoding='utf-8', index=False)